/*
13. write a program to generate 10 random numbers as per the user input range. Count
number of repeated numbers in the list and display.
Output Format:
Enter a number: 34
List: 12,34,34,10,11,22,34,17,14,9
Repeat: 34 repeats 3 times
*/

#include <iostream>
#include <string>
#include <cctype>
#include <random>
#include <unordered_map>

using namespace std;

bool isNumber(const string& str) {
    return !str.empty() &&
           find_if(str.begin(), str.end(), [](unsigned char c) {
             return !std::isdigit(c);
           }) == str.end();
}

int main() {

    int ns;
    string s, output="List: ";
    random_device rdd; //A non-deterministic random nunber generator to generate a random seed. 
    mt19937 rdEngine(rdd()); //Initialize a random engine with the seed generated by calling rdd().


    while (true) {
        output = "List:";

        cout << "Enter a number greater than 10 : " << endl;
        cin >> s;

        if (s == "exit") break;
        
        if (!isNumber(s))
        {
            cout << "Please input not null integer! " << endl;
            continue;
        }
        ns = stoi(s); // convert the input string to integer safely.
        if (ns < 10) continue;
        
        unordered_map<int, int> countMap;
        uniform_int_distribution<> dis(0, ns);
        vector<int> numbers(10);
        for (int& num : numbers) {
            num = dis(rdEngine); //Generate a random number betweeen 0 and ns. 
            countMap[num]++; // Count the occurence frequency of each number.
            if (output != "List: ") {
                output += " , ";
            }
            output += to_string(num);
        }
        cout << output << endl;

        for (const auto& pair : countMap) {
            if (pair.second > 1) {
                cout << pair.first << " repeats " << pair.second << " times" << endl ;
            }
        }
        

    }
    return 0;
}