/*
6. Write a program to store 6 different random numbers in the list between 10 to 20. Allow the
user to find their lucky number in two tries.
*/


#include <iostream>
#include <algorithm>
#include <string>
#include <random>

using namespace std;

bool isNumber(const string& str) {
    return !str.empty() &&
           find_if(str.begin(), str.end(), [](unsigned char c) {
             return !std::isdigit(c);
           }) == str.end();
}

int main() {

    int times = 1;
    vector<int> numbers;
    random_device rdd; //A non-deterministic random nunber generator to generate a random seed. 
    mt19937 rdEngine(rdd()); //Initialize a random engine with the seed generated by calling rdd().
    uniform_int_distribution<> dis(10, 20);


    while (numbers.size() < 6) {
        int num = dis(rdEngine);
        // 确保数字不重复
        if (find(numbers.begin(), numbers.end(), num) == numbers.end()) {
            numbers.push_back(num);
        }
    }
    
    cout << "I have generated 6 random numbers between 10 and 20. " << endl;
    while (times <= 2)
    {
        int guess = 0;
        string s;
        cout << "You have 2 chances to guess one of them. #" << times << ":" << endl;
        cin >> s;

        if (s == "exit") break;
        
        if (!isNumber(s))
        {
            cout << "Please input an integer between 10 and 20! " << endl;
            continue;
        }
        guess = stoi(s); // convert the input string to integer safely.
        if (guess < 10 || guess >20) {
            cout << "Please input an integer between 10 and 20! " << endl;
            continue;
        }
        if (find(numbers.begin(), numbers.end(), guess) != numbers.end()) {
            cout << "Congratulations! You find your luck number!";
        }
        else
        {
            cout << "Sorry!" << guess << " is not a luck number!";
        }
        times++;
    }
    return 0;
}